In [1]:
import pandas as pd

In [2]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'

url = f'{prefix}/yellow_tripdata_2021-01.csv.gz'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow//yellow_tripdata_2021-01.csv.gz'

In [10]:
df = pd.read_csv(url)

/tmp/ipykernel_50641/4176769558.py:1: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [11]:
df.head(5)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [12]:
len(df)

1369765

In [13]:
df.VendorID

0          1.0
1          1.0
2          1.0
3          1.0
4          2.0
          ...
1369760    NaN
1369761    NaN
1369762    NaN
1369763    NaN
1369764    NaN
Name: VendorID, Length: 1369765, dtype: float64

In [14]:
df['tpep_pickup_datetime']

0          2021-01-01 00:30:10
1          2021-01-01 00:51:20
2          2021-01-01 00:43:30
3          2021-01-01 00:15:48
4          2021-01-01 00:31:49
                  ...
1369760    2021-01-25 08:32:04
1369761    2021-01-25 08:34:00
1369762    2021-01-25 08:37:00
1369763    2021-01-25 08:28:00
1369764    2021-01-25 08:38:00
Name: tpep_pickup_datetime, Length: 1369765, dtype: str

In [6]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    nrows=100,
    dtype=dtype,
    parse_dates=parse_dates
)

In [16]:
len(df)

100

In [17]:
!uv add sqlalchemy

Resolved 117 packages in 941ms
Prepared 2 packages in 229ms
░░░░░░░░░░░░░░░░░░░░ [0/2] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 2 packages in 205ms
 + greenlet==3.3.2
 + sqlalchemy==2.0.48

In [19]:
!uv add psycopg2-binary

Resolved 118 packages in 251ms
Prepared 1 package in 127ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 73ms.11
 + psycopg2-binary==2.9.11

In [20]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [21]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

# pd.io.sql.get_schema() : df의 컬럼 type들을 sql에서 사용하는 dtype으로 변환해주는 함수
# name - 생성될 sql 테이블의 이름
# con=engine : 앞서 만든 SQLAlchemy의 engine 객체
# con=engine 파라미터가 있어야 pandas가 postgresql용 문법으로 변환 진행

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [22]:
# head(0) -> schema만 생성
df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [33]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000,
)

In [24]:
df_iter

In [25]:
df = next(df_iter)

In [31]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
1300000,<NA>,2021-01-05 10:38:40,2021-01-05 10:46:20,<NA>,1.30,<NA>,<NA>,170,161,<NA>,7.00,0.00,0.5,1.03,0.00,0.3,11.33,2.5
1300001,<NA>,2021-01-05 10:17:14,2021-01-05 10:41:21,<NA>,7.90,<NA>,<NA>,216,198,<NA>,31.49,0.00,0.5,2.75,0.00,0.3,35.04,0.0
1300002,<NA>,2021-01-05 10:39:00,2021-01-05 10:46:00,<NA>,0.98,<NA>,<NA>,62,62,<NA>,16.23,0.00,0.5,2.75,0.00,0.3,19.78,0.0
1300003,<NA>,2021-01-05 10:05:00,2021-01-05 10:19:00,<NA>,1.59,<NA>,<NA>,85,71,<NA>,13.45,0.00,0.5,2.75,0.00,0.3,17.00,0.0
1300004,<NA>,2021-01-05 10:18:08,2021-01-05 10:41:40,<NA>,9.87,<NA>,<NA>,236,208,<NA>,30.23,0.00,0.5,2.75,6.12,0.3,39.90,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,<NA>,2021-01-25 08:32:04,2021-01-25 08:49:32,<NA>,8.80,<NA>,<NA>,135,82,<NA>,21.84,2.75,0.5,0.00,0.00,0.3,25.39,0.0
1369761,<NA>,2021-01-25 08:34:00,2021-01-25 09:04:00,<NA>,5.86,<NA>,<NA>,42,161,<NA>,26.67,2.75,0.5,0.00,0.00,0.3,30.22,0.0
1369762,<NA>,2021-01-25 08:37:00,2021-01-25 08:53:00,<NA>,4.45,<NA>,<NA>,14,106,<NA>,25.29,2.75,0.5,0.00,0.00,0.3,28.84,0.0
1369763,<NA>,2021-01-25 08:28:00,2021-01-25 08:50:00,<NA>,10.04,<NA>,<NA>,175,216,<NA>,28.24,2.75,0.5,0.00,0.00,0.3,31.79,0.0
1369764,<NA>,2021-01-25 08:38:00,2021-01-25 08:50:00,<NA>,4.93,<NA>,<NA>,248,168,<NA>,20.76,2.75,0.5,0.00,0.00,0.3,24.31,0.0

In [26]:
for df in df_iter:
    print(len(df))

100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
69765

In [27]:
for df_chunk in df_iter:
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

In [28]:
!uv add tqdm

Resolved 119 packages in 0.80ms
Checked 10 packages in 0.20ms

In [29]:
from tqdm.auto import tqdm

In [34]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]